# .github/workflows/secrets-keeper.yml
name: AdelphiSecretKeeper

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  secrets-management:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm ci
    - name: Run SecretsKeeper
      run: node src/index.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
